### ISSUE TITLE
At lecture 20 the code does not work

### ISSUE THREAD

**Issue by wizopizo** [CompleteUnityDeveloper/Number-Wizard-Console-Original#1]
While going through this lesson, section 2 lecture 20, I inputted the void NextGuess function at the bottom. Afterward I went to check just like in the video and my game now doesn't work/doesn't run. I have looked at the code and made sure to have every space, line, even capitalization right but the game will not run. Am I able to get a little help figuring out what went wrong? It will not let me upload the script file, but it is an exact copy of this page (except 18-27 is not skipped)

**Comment by BenTristem** [comment]
Hi there, could you post your question in the Udemy Q&A or at https://community.gamedev.tv with a screenshot of the error so that other students, and ourselves can help you better please.

**Comment by wizopizo** [comment]
will do
